# Site settings
title: The Celestial Loom
email: your-email@domain.com
baseurl: "/"
url: "http://yourdomain.com" # the base hostname & protocol for your site

blog_paragraphs: 5

# Build settings
markdown: kramdown
collections:
  - services
  - signs
  - houses
  - planets
