# RSS feed URL
rss_url: https://nikiastro.wordpress.com/feed/

# Authentication variables
username: foo
password: bar

# Acceptable HTML Tags white list array
HTML_white_list:
  elements:
    - b
    - i
    - strike
    - u
    - a 
    - ul
    - ol
    - blockquote
    - font
    - div
    - img
  attributes:
    - size
    - face